version: '3.8'
services:
  sam_app:
    build:
      context: ./sam_app
      args:
        - HOME
        - USER
        - UID
    user: "${UID}:100"
    command: ["$PWD"]
    ports:
      - "3001:3001"
    volumes:
      - ./sam_app:$HOME
      - /var/run/docker.sock:/var/run/docker.sock

  db:
    image: postgres:12.1
    environment:
      POSTGRES_USER: restro
    ports:
      - '5432:5432'
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./db/seeds.sql:/docker-entrypoint-initdb.d/2-seeds.sql
      - restro-db:/var/lib/postgresql/data

volumes:
  restro-db:
